baseURL = "https://lpython.org/"
languageCode = "en-us"
title = "LPYthon"
theme = "beautifulhugo"
googleAnalytics = "" # update google analytics id

[permalinks]
  blog = "blog/:year/:month/:title/"

[taxonomies]
  tag = "tags"

[Params]
  subtitle = "High performance typed Python compiler"
  readingTime = true
  wordCount = true

[[menu.main]]
    name = "Download"
    url = "download/"
    weight = 1

[[menu.main]]
    name = "Documentation"
    url = "https://docs.lfortran.org/"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "blog/"
    weight = 3
