name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main
    - uses: actions/checkout@v3
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.110.0'
        # extended: true

    - name: Show Hugo version
      shell: bash -l {0}
      run: hugo version

    - name: Build Site
      shell: bash -l {0}
      run: hugo

    - name: GIT Setup Config
      shell: bash -l {0}
      run: |
        git config user.email "noreply@deploy"
        git config user.name "Deploy"

    - name: GIT Checkout gh-pages
      shell: bash -l {0}
      run: |
        cp public/ ../public -r
        git reset --hard
        git fetch origin
        git checkout gh-pages

    - name: Misc Steps
      shell: bash -l {0}
      run: |
        rm -rf *
        mv ../public/* .
        echo "lpython.org" > CNAME

    - name: GIT Add and Commit
      shell: bash -l {0}
      run: |
        git add .
        COMMIT_MESSAGE="Deploying on $(date "+%Y-%m-%d %H:%M:%S")"
        git commit -m "${COMMIT_MESSAGE}"

    - name: GIT Deploy
      run: git push origin gh-pages
